# Generated by Django 2.2 on 2020-07-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartikel',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelartikel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
