# Generated by Django 2.2 on 2020-07-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_auto_20200707_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelartikel',
            old_name='gambar',
            new_name='image',
        ),
    ]
