# Generated by Django 2.2 on 2020-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_auto_20200709_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartikel',
            name='image',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
