# Generated by Django 2.2 on 2020-07-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_auto_20200709_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartikel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
