# Generated by Django 2.2 on 2020-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_auto_20200710_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelartikel',
            name='image',
            field=models.ImageField(default=3, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
